name: Build Mod

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-20.04 # Specifying a version of Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3 # Updated to use the latest stable version
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build # This command runs Gradle to build your mod

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: fabric-mod-jar
          path: build/libs/*.jar # Path to the built jar file

